groups:
  - name: system-alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "Prometheus target {{ $labels.job }} on {{ $labels.instance }} has been down for more than 5 minutes."


      - alert: HighCPUUsage
        expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 85% for more than 10 minutes."


      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 90% for more than 10 minutes."


      - alert: DiskSpaceLow
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.85
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Disk space is low on {{ $labels.device }} at {{ $labels.instance }}"
          description: "Disk usage is above 85% for more than 15 minutes."


      - alert: PrometheusTargetMissing
        expr: absent(up)
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "No targets found"
          description: "Prometheus is not scraping any targets."

