- targets:
    - localhost:9090 
  labels:
    group: 'local-server'  
    region: 'us-east-1'


- targets:
    - 54.242.28.234:9100 #node exporter
    - 54.242.28.234:9115 #blackbox exporter 
    - 54.242.28.234 #nginx 
  labels:
    group: 'worker node 1'  
    region: 'us-east-1'


- targets:
    - 18.212.245.231:9100 #node exporter
    - 18.212.245.231:9115 #blackbox exporter
    - 18.212.245.231:9115 #nginx
  labels:
    group: 'worker node 2'  
    region: 'us-east-1' 

    