- targets:
    - localhost:9090 
    - localhost 
  labels:
    group: 'local-server'  
    region: 'us-east-1'


- targets:
    - 54.147.37.10:9100 #node exporter
    - 54.147.37.10:9115 #blackbox exporter 
    - 54.147.37.10 #home 
  labels:
    group: 'worker node 1'  
    region: 'us-east-1'


- targets:
    - 3.84.184.47:9100 #node exporter
    - 3.84.184.47:9115 #blackbox exporter
    - 13.84.184.47:9115 #home
  labels:
    group: 'worker node 2'  
    region: 'us-east-1' 

    