- name: Configure EC2 instance
  hosts: app #this playbook will run on all the servers
  become: true
  remote_user: root
  vars_files:
    - vars.yml
  vars:
    monitoring_packages:
      - prometheus
      - prometheus-node-exporter
      - prometheus-blackbox-exporter
      - prometheus-alertmanager

    
  tasks:
    - name: Ensure Nginx is installed
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
    
    - name: Ensure Nginx starts on boot
      ansible.builtin.service:
        name: nginx
        enabled: yes

    - name: copy nginx configuration file
      copy:
        src: ./ansible/templates/default #./ansible/templates/prometheus.yml
        dest: /etc/nginx/sites-enabled/default
        #mode: 0644 

    - name: Remove a file
      ansible.builtin.file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: test nginx configuration 
      ansible.builtin.command: nginx -t
      
    - name: restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: Install monitoring packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ monitoring_packages }}"
      become: true

    - name: Ensure Prometheus is running
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ monitoring_packages }}" 

    - name: copy prometheus.yml file
      copy:
        src: ./ansible/templates/prometheus.yml #./ansible/templates/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        mode: 0644 

    - name: copy dynamic target file
      copy:
        src: ./ansible/templates/targets.yml #./ansible/templates/prometheus.yml
        dest: /etc/prometheus/targets.yml
        mode: 0644 

    - name: copy prometheus_alert.yml file
      copy:
        src: ./ansible/templates/prometheus_alert.yml
        dest: /etc/prometheus/prometheus_alert.yml
        owner: prometheus
        group: prometheus
        mode: 0644

    - name: restart prometheus service
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ monitoring_packages }}"