plugin: amazon.aws.aws_ec2
strict: False

regions:
  - us-east-1
filters:
  instance-state-name: running

hostvars:
  ansible_ssh_private_key_file: ~/.ssh/id_rsa
  ansible_user: ubuntu 
  ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

defaults:
host_key_checking : False 


# You need to configure AWS in cli for this to work correctly