name: CI/CD Pipeline
# This workflow is triggered on push events to the main branch


on:
   push:
     branches:
       - main
     paths:
       - 'ansible/**'
       - 'terraform/**'
       - '.github/workflows/**'
 

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}\
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
  
jobs:
 
  deploy:
    name: Build Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test pp
        run: |
         
            sudo npm install 
            sudo npm run build
            sudo npm test
        working-directory: ./app/app

          
